import { Inter } from "next/font/google";
import "./styles/globals.css"
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Surya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-100 flex flex-col">
                <Navbar/>
      
        <div className="h-[calc(100vh-6rem)]">{children}</div>
        
        
        </div>
        </body>
        
    </html>
  );
}
